name: ViaVersion
version: ${version}
description: ${description}
main: moe.caramel.protocolapi.Main
authors: [ LemonCaramel ]
loadbefore: [ ProtocolLib, ProxyPipe, SpigotLib, SkinRestorer ]
softdepend: [ ProtocolSupport, PacketListenerApi ]
website: https://caramel.moe
api-version: 1.16